# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub',
                                       desired_capabilities=DesiredCapabilities.CHROME)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_(self):
        # Test name: Поиск
        # Step # | name | target | value
        # 1 | open | https://www.moscow-restaurants.ru/ |
        self.driver.get("https://www.moscow-restaurants.ru/")
        # 2 | setWindowSize | 900x600 |
        self.driver.set_window_size(900, 600)
        # 3 | click | css=.btn > i |
        self.driver.find_element(By.CSS_SELECTOR, ".btn > i").click()
        # 4 | type | css=.input > input | борщ
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys("борщ")
        # 5 | sendKeys | css=.input > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys(Keys.ENTER)
        # 6 | click | linkText=Борщ с копченой уткой и чесночным багетом в Bird BQ |
        self.driver.find_element(By.LINK_TEXT, "Борщ с копченой уткой и чесночным багетом в Bird BQ").click()
        # 7 | click | css=.btn > i |
        self.driver.find_element(By.CSS_SELECTOR, ".btn > i").click()
        # 8 | type | css=.input > input | уха
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys("уха")
        # 9 | sendKeys | css=.input > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys(Keys.ENTER)
        # 10 | click | linkText=Духан Алаверды |
        self.driver.find_element(By.LINK_TEXT, "Духан Алаверды").click()
        # 11 | click | css=.btn > i |
        self.driver.find_element(By.CSS_SELECTOR, ".btn > i").click()
        # 12 | click | css=.g-inner:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".g-inner:nth-child(2)").click()
        # 13 | click | css=.btn > i |
        self.driver.find_element(By.CSS_SELECTOR, ".btn > i").click()
        # 14 | type | css=.input > input | солянка
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys("солянка")
        # 15 | sendKeys | css=.input > input | ${KEY_ENTER}
        self.driver.find_element(By.CSS_SELECTOR, ".input > input").send_keys(Keys.ENTER)
        # 16 | click | linkText=Солянка сборная в Курорт |
        self.driver.find_element(By.LINK_TEXT, "Солянка сборная в Курорт").click()

    def test_(self):
        # Test name: Предложить ресторан
        # Step # | name | target | value
        # 1 | open | https://www.moscow-restaurants.ru/ |
        self.driver.get("https://www.moscow-restaurants.ru/")
        # 2 | setWindowSize | 1936x1056 |
        self.driver.set_window_size(1936, 1056)
        # 3 | click | css=.col_right:nth-child(4) > .offer:nth-child(2) span |
        self.driver.find_element(By.CSS_SELECTOR, ".col_right:nth-child(4) > .offer:nth-child(2) span").click()
        # 4 | click | css=#popup_offer li:nth-child(1) > input |
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(1) > input").click()
        # 5 | type | css=#popup_offer li:nth-child(1) > input | Шляпа Боярского
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(1) > input").send_keys("Шляпа Боярского")
        # 6 | click | css=#popup_offer li:nth-child(2) > input |
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(2) > input").click()
        # 7 | type | css=#popup_offer li:nth-child(2) > input | ул. ХЗ, д. 3
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(2) > input").send_keys("ул. ХЗ, д. 3")
        # 8 | click | css=#popup_offer li:nth-child(3) > input |
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(3) > input").click()
        # 9 | type | css=#popup_offer li:nth-child(3) > input | Жральня
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer li:nth-child(3) > input").send_keys("Жральня")
        # 10 | click | name=person |
        self.driver.find_element(By.NAME, "person").click()
        # 11 | type | name=person | Вазген
        self.driver.find_element(By.NAME, "person").send_keys("Вазген")
        # 12 | click | name=email |
        self.driver.find_element(By.NAME, "email").click()
        # 13 | type | name=email | zhradlo@ya.ru
        self.driver.find_element(By.NAME, "email").send_keys("zhradlo@ya.ru")
        # 14 | click | css=li:nth-child(6) .text-input |
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) .text-input").click()
        # 15 | click | id=nc_captcha_refresh_button0 |
        self.driver.find_element(By.ID, "nc_captcha_refresh_button0").click()
        # 16 | click | id=nc_captcha_refresh_button0 |
        self.driver.find_element(By.ID, "nc_captcha_refresh_button0").click()
        # 17 | click | css=li:nth-child(6) .text-input |
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) .text-input").click()
        # 18 | type | css=li:nth-child(6) .text-input | MGNUY
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) .text-input").send_keys("MGNUY")
        # 19 | click | css=#popup_offer span |
        self.driver.find_element(By.CSS_SELECTOR, "#popup_offer span").click()

    def test_(self):
        # Test name: рейтинг
        # Step # | name | target | value
        # 1 | open | https://www.moscow-restaurants.ru/ |
        self.driver.get("https://www.moscow-restaurants.ru/")
        # 2 | setWindowSize | 1936x1056 |
        self.driver.set_window_size(1936, 1056)
        # 3 | click | css=.g-outer:nth-child(2) li:nth-child(4) .text |
        self.driver.find_element(By.CSS_SELECTOR, ".g-outer:nth-child(2) li:nth-child(4) .text").click()
        # 4 | click | linkText=обзоры ресторанов |
        self.driver.find_element(By.LINK_TEXT, "обзоры ресторанов").click()
        # 5 | click | linkText=Рейтинг |
        self.driver.find_element(By.LINK_TEXT, "Рейтинг").click()
        # 6 | click | css=.selection-made |
        self.driver.find_element(By.CSS_SELECTOR, ".selection-made").click()
        # 7 | click | linkText=Авторская кухня |
        self.driver.find_element(By.LINK_TEXT, "Авторская кухня").click()
        # 8 | click | linkText=Лучшие |
        self.driver.find_element(By.LINK_TEXT, "Лучшие").click()
        # 9 | click | css=.selection-made |
        self.driver.find_element(By.CSS_SELECTOR, ".selection-made").click()
        # 10 | click | linkText=2022 |
        self.driver.find_element(By.LINK_TEXT, "2022").click()
        # 11 | click | css=li:nth-child(3) .fn |
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) .fn").click()
        # 12 | click | css=.logo-col_2 > .text_2 |
        self.driver.find_element(By.CSS_SELECTOR, ".logo-col_2 > .text_2").click()
        # 13 | click | css=.logo-col_1 img |
        self.driver.find_element(By.CSS_SELECTOR, ".logo-col_1 img").click()
